version: "2"
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupl
    - embeddedstructfieldcheck
    - err113
    - errorlint
    - exhaustruct
    - exhaustive
    - gocognit
    - gocyclo
    - gosec
    - interfacebloat
    - ireturn
    - mnd
    - nakedret
    - nestif
    - nilerr
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - thelper
    - varnamelen
    - wrapcheck
    - wsl_v5
  settings:
    dupl:
      threshold: 100
    funlen:
      lines: 120
      statements: 60
    goconst:
      min-len: 2
      min-occurrences: 4
    gocritic:
      disabled-checks:
        - preferStringWriter
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    govet:
      disable:
        - fieldalignment
      enable-all: true
    lll:
      line-length: 140
    misspell:
      locale: US
    revive:
      rules:
        - name: cyclomatic
          arguments:
            - 20
          severity: warning
        - name: line-length-limit
          arguments:
            - 140
          severity: error
        - name: unused-parameter
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
          - staticcheck
        text: .*id.* should be .*ID.*
      - linters:
          - godox
        text: Line contains TODO/BUG/FIXME
      - linters:
          - revive
        path: test
        text: 'cyclomatic:'
      - linters:
          - dogsled
          - dupl
          - funlen
          - goconst
          - gocritic
          - maintidx
        path: test
      - linters:
          - staticcheck
        text: 'S1040: type assertion to the same type'
      - linters:
          - staticcheck
        text: "QF1001: could apply De Morgan's law"
      - linters:
          - gocritic
          - intrange
          - revive
        path: vfs_ostype_on.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
