// Code generated by "stringer -type Feature -trimprefix Feat -bitmask -output avfs_feature.go"; DO NOT EDIT.

package avfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FeatBasicFs-1]
	_ = x[FeatChroot-2]
	_ = x[FeatMainDirs-4]
	_ = x[FeatHardlink-8]
	_ = x[FeatIdentityMgr-16]
	_ = x[FeatReadOnly-32]
	_ = x[FeatRealFS-64]
	_ = x[FeatSymlink-128]
}

const _Feature_name = "BasicFsChrootMainDirsHardlinkIdentityMgrReadOnlyRealFSSymlink"

var _Feature_map = map[Feature]string{
	1:   _Feature_name[0:7],
	2:   _Feature_name[7:13],
	4:   _Feature_name[13:21],
	8:   _Feature_name[21:29],
	16:  _Feature_name[29:40],
	32:  _Feature_name[40:48],
	64:  _Feature_name[48:54],
	128: _Feature_name[54:61],
}

func (i Feature) String() string {
	if i <= 0 {
		return "Feature()"
	}
	sb := make([]byte, 0, len(_Feature_name)/2)
	sb = append(sb, []byte("Feature(")...)
	for mask := Feature(1); mask > 0 && mask <= i; mask <<= 1 {
		val := i & mask
		if val == 0 {
			continue
		}
		str, ok := _Feature_map[val]
		if !ok {
			str = "0x" + strconv.FormatUint(uint64(val), 16)
		}
		sb = append(sb, []byte(str)...)
		sb = append(sb, '|')
	}
	sb[len(sb)-1] = ')'
	return string(sb)
}
