// Code generated by "stringer -type WindowsError -linecomment -output errors_forwindows.go"; DO NOT EDIT.

package avfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrWinAccessDenied-5]
	_ = x[ErrWinAlreadyExists-183]
	_ = x[ErrWinDirNameInvalid-267]
	_ = x[ErrWinDirNotEmpty-145]
	_ = x[ErrWinFileExists-80]
	_ = x[ErrWinFileNotFound-2]
	_ = x[ErrWinIsADirectory-21]
	_ = x[ErrWinNegativeSeek-131]
	_ = x[ErrWinNotReparsePoint-4390]
	_ = x[ErrWinInvalidHandle-6]
	_ = x[ErrWinNotSupported-536871042]
	_ = x[ErrWinPathNotFound-3]
	_ = x[ErrWinPrivilegeNotHeld-1314]
}

const _WindowsError_name = "The system cannot find the file specified.The system cannot find the path specified.Access is denied.The handle is invalid.is a directoryThe file exists.An attempt was made to move the file pointer before the beginning of the file.The directory is not empty.Cannot create a file when that file already exists.The directory name is invalid.A required privilege is not held by the client.The file or directory is not a reparse point.not supported by windows"

var _WindowsError_map = map[WindowsError]string{
	2:         _WindowsError_name[0:42],
	3:         _WindowsError_name[42:84],
	5:         _WindowsError_name[84:101],
	6:         _WindowsError_name[101:123],
	21:        _WindowsError_name[123:137],
	80:        _WindowsError_name[137:153],
	131:       _WindowsError_name[153:231],
	145:       _WindowsError_name[231:258],
	183:       _WindowsError_name[258:309],
	267:       _WindowsError_name[309:339],
	1314:      _WindowsError_name[339:386],
	4390:      _WindowsError_name[386:431],
	536871042: _WindowsError_name[431:455],
}

func (i WindowsError) String() string {
	if str, ok := _WindowsError_map[i]; ok {
		return str
	}
	return "WindowsError(" + strconv.FormatInt(int64(i), 10) + ")"
}
