// Code generated by "stringer -type CustomError -linecomment -output errors_custom.go"; DO NOT EDIT.

package avfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNegativeOffset-2147483646]
	_ = x[ErrFileClosing-2147483645]
	_ = x[ErrPatternHasSeparator-2147483644]
	_ = x[ErrVolumeAlreadyExists-2147483643]
	_ = x[ErrVolumeNameInvalid-2147483642]
	_ = x[ErrVolumeWindows-2147483641]
	_ = x[ErrNotSupported-2147483640]
}

const _CustomError_name = "The operation is not supported.Volumes are available for Windows only.Volume name is invalid.Volume already exists.pattern contains path separatoruse of closed filenegative offset"

var _CustomError_index = [...]uint8{0, 31, 70, 93, 115, 146, 164, 179}

func (i CustomError) String() string {
	idx := int(i) - 2147483640
	if i < 2147483640 || idx >= len(_CustomError_index)-1 {
		return "CustomError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CustomError_name[_CustomError_index[idx]:_CustomError_index[idx+1]]
}
