// Code generated by "stringer -type CustomError -linecomment -output errors_custom.go"; DO NOT EDIT.

package avfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrNegativeOffset-2147483649]
	_ = x[ErrFileClosing-2147483650]
	_ = x[ErrPatternHasSeparator-2147483651]
	_ = x[ErrVolumeAlreadyExists-2147483652]
	_ = x[ErrVolumeNameInvalid-2147483653]
	_ = x[ErrVolumeWindows-2147483654]
}

const _CustomError_name = "negative offsetuse of closed filepattern contains path separatorVolume already exists.Volume name is invalid.Volumes are available for Windows only."

var _CustomError_index = [...]uint8{0, 15, 33, 64, 86, 109, 148}

func (i CustomError) String() string {
	idx := int(i) - 2147483649
	if i < 2147483649 || idx >= len(_CustomError_index)-1 {
		return "CustomError(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CustomError_name[_CustomError_index[idx]:_CustomError_index[idx+1]]
}
