// Code generated by "stringer -type FnVFS -trimprefix Fn -output fnvfs_string.go"; DO NOT EDIT.

package avfs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FnAbs-1]
	_ = x[FnChdir-2]
	_ = x[FnChmod-3]
	_ = x[FnChown-4]
	_ = x[FnChtimes-5]
	_ = x[FnCreateTemp-6]
	_ = x[FnEvalSymlinks-7]
	_ = x[FnFileChdir-8]
	_ = x[FnFileChmod-9]
	_ = x[FnFileChown-10]
	_ = x[FnFileClose-11]
	_ = x[FnFileRead-12]
	_ = x[FnFileReadAt-13]
	_ = x[FnFileReadDir-14]
	_ = x[FnFileReaddirnames-15]
	_ = x[FnFileSeek-16]
	_ = x[FnFileStat-17]
	_ = x[FnFileSync-18]
	_ = x[FnFileTruncate-19]
	_ = x[FnFileWrite-20]
	_ = x[FnFileWriteAt-21]
	_ = x[FnGetwd-22]
	_ = x[FnLchown-23]
	_ = x[FnLink-24]
	_ = x[FnLstat-25]
	_ = x[FnMkdir-26]
	_ = x[FnMkdirAll-27]
	_ = x[FnMkdirTemp-28]
	_ = x[FnOpenFile-29]
	_ = x[FnReadDir-30]
	_ = x[FnReadFile-31]
	_ = x[FnReadlink-32]
	_ = x[FnRemove-33]
	_ = x[FnRemoveAll-34]
	_ = x[FnRename-35]
	_ = x[FnSetUser-36]
	_ = x[FnSetUserByName-37]
	_ = x[FnStat-38]
	_ = x[FnSub-39]
	_ = x[FnSymlink-40]
	_ = x[FnTruncate-41]
	_ = x[FnWalkDir-42]
	_ = x[FnWriteFile-43]
}

const _FnVFS_name = "AbsChdirChmodChownChtimesCreateTempEvalSymlinksFileChdirFileChmodFileChownFileCloseFileReadFileReadAtFileReadDirFileReaddirnamesFileSeekFileStatFileSyncFileTruncateFileWriteFileWriteAtGetwdLchownLinkLstatMkdirMkdirAllMkdirTempOpenFileReadDirReadFileReadlinkRemoveRemoveAllRenameSetUserSetUserByNameStatSubSymlinkTruncateWalkDirWriteFile"

var _FnVFS_index = [...]uint16{0, 3, 8, 13, 18, 25, 35, 47, 56, 65, 74, 83, 91, 101, 112, 128, 136, 144, 152, 164, 173, 184, 189, 195, 199, 204, 209, 217, 226, 234, 241, 249, 257, 263, 272, 278, 285, 298, 302, 305, 312, 320, 327, 336}

func (i FnVFS) String() string {
	i -= 1
	if i >= FnVFS(len(_FnVFS_index)-1) {
		return "FnVFS(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _FnVFS_name[_FnVFS_index[i]:_FnVFS_index[i+1]]
}
