//
//  Copyright 2024 The AVFS authors
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

// Package failfs is a file system adapter to test failures in a base file system.
//
// Failures are generated by returning an error in a custom function of type FailFunc.
// This functions should be set using FailFS.SetFailFunc.
package failfs

import (
	"io/fs"
	"os"
	"time"

	"github.com/avfs/avfs"
)

// Abs returns an absolute representation of path.
// If the path is not absolute it will be joined with the current
// working directory to turn it into an absolute path. The absolute
// path name for a given file is not guaranteed to be unique.
// Abs calls [Clean] on the result.
func (vfs *FailFS) Abs(path string) (string, error) {
	fp := FailParam{Op: "abs", Path: path}

	err := vfs.fail(avfs.FnAbs, &fp)
	if err != nil {
		return "", err
	}

	return vfs.baseFS.Abs(path)
}

// Base returns the last element of path.
// Trailing path separators are removed before extracting the last element.
// If the path is empty, Base returns ".".
// If the path consists entirely of separators, Base returns a single separator.
func (vfs *FailFS) Base(path string) string {
	return vfs.baseFS.Base(path)
}

// Chdir changes the current working directory to the named directory.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Chdir(dir string) error {
	fp := FailParam{Op: "chdir", Path: dir}

	err := vfs.fail(avfs.FnChdir, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Chdir(dir)
}

// Chmod changes the mode of the named file to mode.
// If the file is a symbolic link, it changes the mode of the link's target.
// If there is an error, it will be of type *PathError.
//
// A different subset of the mode bits are used, depending on the
// operating system.
//
// On Unix, the mode's permission bits, ModeSetuid, ModeSetgid, and
// ModeSticky are used.
//
// On Windows, only the 0200 bit (owner writable) of mode is used; it
// controls whether the file's read-only attribute is set or cleared.
// The other bits are currently unused. For compatibility with Go 1.12
// and earlier, use a non-zero mode. Use mode 0400 for a read-only
// file and 0600 for a readable+writable file.
//
// On Plan 9, the mode's permission bits, ModeAppend, ModeExclusive,
// and ModeTemporary are used.
func (vfs *FailFS) Chmod(name string, mode fs.FileMode) error {
	fp := FailParam{Op: "chmod", Path: name, Perm: mode}

	err := vfs.fail(avfs.FnChmod, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Chmod(name, mode)
}

// Chown changes the numeric uid and gid of the named file.
// If the file is a symbolic link, it changes the uid and gid of the link's target.
// A uid or gid of -1 means to not change that value.
// If there is an error, it will be of type *PathError.
//
// On Windows or Plan 9, Chown always returns the syscall.EWINDOWS or
// EPLAN9 error, wrapped in *PathError.
func (vfs *FailFS) Chown(name string, uid, gid int) error {
	fp := FailParam{Op: "chown", Path: name, Uid: uid, Gid: gid}

	err := vfs.fail(avfs.FnChown, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Chown(name, uid, gid)
}

// Chtimes changes the access and modification times of the named
// file, similar to the Unix utime() or utimes() functions.
//
// The underlying file system may truncate or round the values to a
// less precise time unit.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Chtimes(name string, atime, mtime time.Time) error {
	fp := FailParam{Op: "chtimes", Path: name, ATime: atime, MTime: mtime}

	err := vfs.fail(avfs.FnChtimes, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Chtimes(name, atime, mtime)
}

// Clean returns the shortest path name equivalent to path
// by purely lexical processing. It applies the following rules
// iteratively until no further processing can be done:
//
//  1. Replace multiple Separator elements with a single one.
//  2. Eliminate each . path name element (the current directory).
//  3. Eliminate each inner .. path name element (the parent directory)
//     along with the non-.. element that precedes it.
//  4. Eliminate .. elements that begin a rooted path:
//     that is, replace "/.." by "/" at the beginning of a path,
//     assuming Separator is '/'.
//
// The returned path ends in a slash only if it represents a root directory,
// such as "/" on Unix or `C:\` on Windows.
//
// Finally, any occurrences of slash are replaced by Separator.
//
// If the result of this process is an empty string, Clean
// returns the string ".".
//
// See also Rob Pike, “Lexical File Names in Plan 9 or
// Getting Dot-Dot Right,”
// https://9p.io/sys/doc/lexnames.html
func (vfs *FailFS) Clean(path string) string {
	return avfs.Clean(vfs, path)
}

// Create creates or truncates the named file. If the file already exists,
// it is truncated. If the file does not exist, it is created with mode 0666
// (before umask). If successful, methods on the returned DummyFile can
// be used for I/O; the associated file descriptor has mode O_RDWR.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Create(name string) (avfs.File, error) {
	return avfs.Create(vfs, name)
}

// CreateTemp creates a new temporary file in the directory dir,
// opens the file for reading and writing, and returns the resulting file.
// The filename is generated by taking pattern and adding a random string to the end.
// If pattern includes a "*", the random string replaces the last "*".
// If dir is the empty string, CreateTemp uses the default directory for temporary files, as returned by TempDir.
// Multiple programs or goroutines calling CreateTemp simultaneously will not choose the same file.
// The caller can use the file's Name method to find the pathname of the file.
// It is the caller's responsibility to remove the file when it is no longer needed.
func (vfs *FailFS) CreateTemp(dir, pattern string) (avfs.File, error) {
	fp := FailParam{Op: "createtemp", Path: dir}

	err := vfs.fail(avfs.FnCreateTemp, &fp)
	if err != nil {
		return &FailFile{}, err
	}

	return vfs.baseFS.CreateTemp(dir, pattern)
}

// Dir returns all but the last element of path, typically the path's directory.
// After dropping the final element, Dir calls Clean on the path and trailing
// slashes are removed.
// If the path is empty, Dir returns ".".
// If the path consists entirely of separators, Dir returns a single separator.
// The returned path does not end in a separator unless it is the root directory.
func (vfs *FailFS) Dir(path string) string {
	return avfs.Dir(vfs, path)
}

// EvalSymlinks returns the path name after the evaluation of any symbolic
// links.
// If path is relative the result will be relative to the current directory,
// unless one of the components is an absolute symbolic link.
// EvalSymlinks calls Clean on the result.
func (vfs *FailFS) EvalSymlinks(path string) (string, error) {
	fp := FailParam{Op: "evalsymlinks", Path: path}

	err := vfs.fail(avfs.FnEvalSymlinks, &fp)
	if err != nil {
		return "", err
	}

	return vfs.baseFS.EvalSymlinks(path)
}

// FromSlash returns the result of replacing each slash ('/') character
// in path with a separator character. Multiple slashes are replaced
// by multiple separators.
func (vfs *FailFS) FromSlash(path string) string {
	return avfs.FromSlash(vfs, path)
}

// Getwd returns a rooted name link corresponding to the
// current directory. If the current directory can be
// reached via multiple paths (due to symbolic links),
// Getwd may return any one of them.
func (vfs *FailFS) Getwd() (dir string, err error) {
	fp := FailParam{Op: "getwd"}

	err = vfs.fail(avfs.FnGetwd, &fp)
	if err != nil {
		return "", err
	}

	return vfs.baseFS.Getwd()
}

// Glob returns the names of all files matching pattern or nil
// if there is no matching file. The syntax of patterns is the same
// as in Match. The pattern may describe hierarchical names such as
// /usr/*/bin/ed (assuming the Separator is '/').
//
// Glob ignores file system errors such as I/O errors reading directories.
// The only possible returned error is ErrBadPattern, when pattern
// is malformed.
func (vfs *FailFS) Glob(pattern string) (matches []string, err error) {
	return avfs.Glob(vfs, pattern)
}

func (vfs *FailFS) Idm() avfs.IdentityMgr {
	return vfs.baseFS.Idm()
}

// IsAbs reports whether the path is absolute.
func (vfs *FailFS) IsAbs(path string) bool {
	return avfs.IsAbs(vfs, path)
}

// IsPathSeparator reports whether c is a directory separator character.
func (vfs *FailFS) IsPathSeparator(c uint8) bool {
	return avfs.IsPathSeparator(vfs, c)
}

// Join joins any number of path elements into a single path,
// separating them with an OS specific Separator. Empty elements
// are ignored. The result is Cleaned. However, if the argument
// list is empty or all its elements are empty, Join returns
// an empty string.
// On Windows, the result will only be a UNC path if the first
// non-empty element is a UNC path.
func (vfs *FailFS) Join(elem ...string) string {
	return avfs.Join(vfs, elem...)
}

// Lchown changes the numeric uid and gid of the named file.
// If the file is a symbolic link, it changes the uid and gid of the link itself.
// If there is an error, it will be of type *PathError.
//
// On Windows, it always returns the syscall.EWINDOWS error, wrapped
// in *PathError.
func (vfs *FailFS) Lchown(name string, uid, gid int) error {
	fp := FailParam{Op: "lchown", Path: name, Uid: uid, Gid: gid}

	err := vfs.fail(avfs.FnLchown, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Lchown(name, uid, gid)
}

// Link creates newname as a hard link to the oldname file.
// If there is an error, it will be of type *LinkError.
func (vfs *FailFS) Link(oldname, newname string) error {
	fp := FailParam{Op: "link", Path: oldname, NewPath: newname}

	err := vfs.fail(avfs.FnLink, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Link(oldname, newname)
}

// Lstat returns a FileInfo describing the named file.
// If the file is a symbolic link, the returned FileInfo
// describes the symbolic link. Lstat makes no attempt to follow the link.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Lstat(name string) (fs.FileInfo, error) {
	fp := FailParam{Op: "lstat", Path: name}

	err := vfs.fail(avfs.FnLstat, &fp)
	if err != nil {
		return nil, err
	}

	return vfs.baseFS.Lstat(name)
}

// Match reports whether name matches the shell file name pattern.
// The pattern syntax is:
//
//	pattern:
//		{ term }
//	term:
//		'*'         matches any sequence of non-Separator characters
//		'?'         matches any single non-Separator character
//		'[' [ '^' ] { character-range } ']'
//		            character class (must be non-empty)
//		c           matches character c (c != '*', '?', '\\', '[')
//		'\\' c      matches character c
//
//	character-range:
//		c           matches character c (c != '\\', '-', ']')
//		'\\' c      matches character c
//		lo '-' hi   matches character c for lo <= c <= hi
//
// Match requires pattern to match all of name, not just a substring.
// The only possible returned error is ErrBadPattern, when pattern
// is malformed.
//
// On Windows, escaping is disabled. Instead, '\\' is treated as
// path separator.
func (vfs *FailFS) Match(pattern, name string) (matched bool, err error) {
	return avfs.Match(vfs, pattern, name)
}

// Mkdir creates a new directory with the specified name and permission
// bits (before umask).
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Mkdir(name string, perm fs.FileMode) error {
	fp := FailParam{Op: "mkdir", Path: name, Perm: perm}

	err := vfs.fail(avfs.FnMkdir, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Mkdir(name, perm)
}

// MkdirAll creates a directory named name,
// along with any necessary parents, and returns nil,
// or else returns an error.
// The permission bits perm (before umask) are used for all
// directories that MkdirAll creates.
// If name is already a directory, MkdirAll does nothing
// and returns nil.
func (vfs *FailFS) MkdirAll(path string, perm fs.FileMode) error {
	fp := FailParam{Op: "mkdir", Path: path, Perm: perm}

	err := vfs.fail(avfs.FnMkdirAll, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.MkdirAll(path, perm)
}

// MkdirTemp creates a new temporary directory in the directory dir
// and returns the pathname of the new directory.
// The new directory's name is generated by adding a random string to the end of pattern.
// If pattern includes a "*", the random string replaces the last "*" instead.
// If dir is the empty string, MkdirTemp uses the default directory for temporary files, as returned by TempDir.
// Multiple programs or goroutines calling MkdirTemp simultaneously will not choose the same directory.
// It is the caller's responsibility to remove the directory when it is no longer needed.
func (vfs *FailFS) MkdirTemp(dir, pattern string) (string, error) {
	fp := FailParam{Op: "mkdirtemp", Path: dir}

	err := vfs.fail(avfs.FnMkdirTemp, &fp)
	if err != nil {
		return "", err
	}

	return avfs.MkdirTemp(vfs, dir, pattern)
}

// Open opens the named file for reading. If successful, methods on
// the returned file can be used for reading; the associated file
// descriptor has mode O_RDONLY.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Open(name string) (avfs.File, error) {
	return vfs.OpenFile(name, os.O_RDONLY, 0)
}

// OpenFile is the generalized open call; most users will use Open
// or Create instead. It opens the named file with specified flag
// (O_RDONLY etc.). If the file does not exist, and the O_CREATE flag
// is passed, it is created with mode perm (before umask). If successful,
// methods on the returned File can be used for I/O.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) OpenFile(name string, flag int, perm fs.FileMode) (avfs.File, error) {
	fp := FailParam{Op: "open", Path: name, Flag: flag, Perm: perm}

	err := vfs.fail(avfs.FnOpenFile, &fp)
	if err != nil {
		return &FailFile{}, err
	}

	bf, err := vfs.baseFS.OpenFile(name, flag, perm)

	f := &FailFile{
		baseFile: bf,
		vfs:      vfs,
	}

	return f, err
}

func (vfs *FailFS) OSType() avfs.OSType {
	return vfs.baseFS.OSType()
}

func (vfs *FailFS) PathSeparator() uint8 {
	return vfs.baseFS.PathSeparator()
}

// ReadDir reads the named directory,
// returning all its directory entries sorted by filename.
// If an error occurs reading the directory,
// ReadDir returns the entries it was able to read before the error,
// along with the error.
func (vfs *FailFS) ReadDir(name string) ([]fs.DirEntry, error) {
	fp := FailParam{Op: "readdir", Path: name}

	err := vfs.fail(avfs.FnReadDir, &fp)
	if err != nil {
		return nil, err
	}

	return avfs.ReadDir(vfs, name)
}

// ReadFile reads the named file and returns the contents.
// A successful call returns err == nil, not err == EOF.
// Because ReadFile reads the whole file, it does not treat an EOF from Read
// as an error to be reported.
func (vfs *FailFS) ReadFile(name string) ([]byte, error) {
	fp := FailParam{Op: "readfile", Path: name}

	err := vfs.fail(avfs.FnReadFile, &fp)
	if err != nil {
		return nil, err
	}

	return avfs.ReadFile(vfs, name)
}

// Readlink returns the destination of the named symbolic link.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Readlink(name string) (string, error) {
	fp := FailParam{Op: "readlink", Path: name}

	err := vfs.fail(avfs.FnReadlink, &fp)
	if err != nil {
		return "", err
	}

	return vfs.baseFS.Readlink(name)
}

// Rel returns a relative path that is lexically equivalent to targpath when
// joined to basepath with an intervening separator. That is,
// Join(basepath, Rel(basepath, targpath)) is equivalent to targpath itself.
// On success, the returned path will always be relative to basepath,
// even if basepath and targpath share no elements.
// An error is returned if targpath can't be made relative to basepath or if
// knowing the current working directory would be necessary to compute it.
// Rel calls Clean on the result.
func (vfs *FailFS) Rel(basepath, targpath string) (string, error) {
	return avfs.Rel(vfs, basepath, targpath)
}

// Remove removes the named file or (empty) directory.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Remove(name string) error {
	fp := FailParam{Op: "remove", Path: name}

	err := vfs.fail(avfs.FnRemove, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Remove(name)
}

// RemoveAll removes path and any children it contains.
// It removes everything it can but returns the first error
// it encounters. If the path does not exist, RemoveAll
// returns nil (no error).
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) RemoveAll(path string) error {
	fp := FailParam{Op: "removeall", Path: path}

	err := vfs.fail(avfs.FnRemoveAll, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.RemoveAll(path)
}

// Rename renames (moves) oldpath to newpath.
// If newpath already exists and is not a directory, Rename replaces it.
// OS-specific restrictions may apply when oldpath and newpath are in different directories.
// If there is an error, it will be of type *LinkError.
func (vfs *FailFS) Rename(oldname, newname string) error {
	fp := FailParam{Op: "rename", Path: oldname, NewPath: newname}

	err := vfs.fail(avfs.FnRename, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Rename(oldname, newname)
}

// SameFile reports whether fi1 and fi2 describe the same file.
// For example, on Unix this means that the device and inode fields
// of the two underlying structures are identical; on other systems
// the decision may be based on the path names.
// SameFile only applies to results returned by this package's Stat.
// It returns false in other cases.
func (vfs *FailFS) SameFile(fi1, fi2 fs.FileInfo) bool {
	return vfs.baseFS.SameFile(fi1, fi2)
}

// SetFailFunc sets the FailFunc function.
func (vfs *FailFS) SetFailFunc(ff FailFunc) error {
	vfs.failFunc = ff

	return nil
}

func (vfs *FailFS) SetIdm(idm avfs.IdentityMgr) error {
	return vfs.baseFS.SetIdm(idm)
}

func (vfs *FailFS) SetUMask(mask fs.FileMode) error {
	return vfs.baseFS.SetUMask(mask)
}

func (vfs *FailFS) SetUser(user avfs.UserReader) error {
	fp := FailParam{Path: user.Name()}

	err := vfs.fail(avfs.FnSetUser, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.SetUser(user)
}

// SetUserByName sets the current user by name.
// If the user is not found, the returned error is of type UnknownUserError.
func (vfs *FailFS) SetUserByName(name string) error {
	fp := FailParam{Path: name}

	err := vfs.fail(avfs.FnSetUserByName, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.SetUserByName(name)
}

// Split splits path immediately following the final Separator,
// separating it into a directory and file name component.
// If there is no Separator in path, Split returns an empty dir
// and file set to path.
// The returned values have the property that path = dir+file.
func (vfs *FailFS) Split(path string) (dir, file string) {
	return avfs.Split(vfs, path)
}

// Stat returns a FileInfo describing the named file.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Stat(path string) (fs.FileInfo, error) {
	fp := FailParam{Op: "stat", Path: path}

	err := vfs.fail(avfs.FnStat, &fp)
	if err != nil {
		return nil, err
	}

	return vfs.baseFS.Stat(path)
}

// Sub returns an FS corresponding to the subtree rooted at dir.
func (vfs *FailFS) Sub(dir string) (avfs.VFS, error) {
	fp := FailParam{Op: "sub", Path: dir}

	err := vfs.fail(avfs.FnSub, &fp)
	if err != nil {
		return nil, err
	}

	return vfs.baseFS.Sub(dir)
}

// Symlink creates newname as a symbolic link to oldname.
// If there is an error, it will be of type *LinkError.
func (vfs *FailFS) Symlink(oldname, newname string) error {
	fp := FailParam{Op: "symlink", Path: oldname, NewPath: newname}

	err := vfs.fail(avfs.FnSymlink, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Symlink(oldname, newname)
}

// TempDir returns the default directory to use for temporary files.
//
// On Unix systems, it returns $TMPDIR if non-empty, else /tmp.
// On Windows, it uses GetTempPath, returning the first non-empty
// value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory.
// On Plan 9, it returns /tmp.
//
// The directory is neither guaranteed to exist nor have accessible
// permissions.
func (vfs *FailFS) TempDir() string {
	return avfs.TempDir(vfs)
}

// ToSlash returns the result of replacing each separator character
// in path with a slash ('/') character. Multiple separators are
// replaced by multiple slashes.
func (vfs *FailFS) ToSlash(path string) string {
	return avfs.ToSlash(vfs, path)
}

// ToSysStat takes a value from fs.FileInfo.Sys() and returns a value that implements interface avfs.SysStater.
func (vfs *FailFS) ToSysStat(info fs.FileInfo) avfs.SysStater {
	return info.Sys().(avfs.SysStater) //nolint:forcetypeassert // type assertion must be checked
}

// Truncate changes the size of the named file.
// If the file is a symbolic link, it changes the size of the link's target.
// If there is an error, it will be of type *PathError.
func (vfs *FailFS) Truncate(name string, size int64) error {
	fp := FailParam{Op: "truncate", Path: name, Size: size}

	err := vfs.fail(avfs.FnTruncate, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.Truncate(name, size)
}

func (vfs *FailFS) UMask() fs.FileMode {
	return vfs.baseFS.UMask()
}

func (vfs *FailFS) User() avfs.UserReader {
	return vfs.baseFS.User()
}

// WalkDir walks the file tree rooted at root, calling fn for each file or
// directory in the tree, including root.
//
// All errors that arise visiting files and directories are filtered by fn:
// see the fs.WalkDirFunc documentation for details.
//
// The files are walked in lexical order, which makes the output deterministic
// but requires WalkDir to read an entire directory into memory before proceeding
// to walk that directory.
//
// WalkDir does not follow symbolic links.
func (vfs *FailFS) WalkDir(root string, fn fs.WalkDirFunc) error {
	fp := FailParam{Op: "walkdir", Path: root}

	err := vfs.fail(avfs.FnWalkDir, &fp)
	if err != nil {
		return err
	}

	return vfs.baseFS.WalkDir(root, fn)
}

// WriteFile writes data to the named file, creating it if necessary.
// If the file does not exist, WriteFile creates it with permissions perm (before umask);
// otherwise WriteFile truncates it before writing, without changing permissions.
func (vfs *FailFS) WriteFile(name string, data []byte, perm fs.FileMode) error {
	return avfs.WriteFile(vfs, name, data, perm)
}
