name: CI
on:
  push:
    branch:
      tags-ignore:
        - v[0-9]+\.[0-9]+\.[0-9]+
    pull_request:

jobs:
  test:
    env :
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.13.x, 1.14.x]
        ## TODO: os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: ${{ matrix.go-version }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.28

      - name: Install mage & avfs binaries
        run: go run mage/build.go

      - name: Run tests as root on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        # preserve user environment variables :
        # for some reason go version as root is different from user version.
        run: sudo -E env "PATH=$PATH" avfs test

      - name: Run tests on non linux systems
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}
        run: avfs test

      - name: Upload linux coverage to Codecov
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
