name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [1.20.x]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v3

      - name: Install mage & avfs binaries
        run: go run mage/build.go

      - name: Run tests as an unprivileged user
        run: avfs test

      - name: Run tests as root
        run: avfs testAsRoot

      - name: Run tests as root with SetOsType
        env:
          GOFLAGS: "-tags=avfs_setostype"
        run: avfs testAsRoot

      - name: Run race tests
        run: avfs race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        env:
          OS: ${{ matrix.os }}
          GO: ${{ matrix.go }}
        with:
          files: tmp/avfs-cover-*.txt
          env_vars: OS,GO
          verbose: true

      - name: Run build tests on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: avfs testbuild

