name: CI
on: [push, pull_request]

jobs:
  test:
    env :
      GO111MODULE: on
    strategy:
      fail-fast: false
      matrix:
        go: [1.16.x]
        ## TODO: os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v2

      - name: Install mage & avfs binaries
        run: go run mage/build.go

      - name: Run tests as root on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        # preserve user environment variables :
        # for some reason go version as root is different from user version.
        run: sudo -E env "PATH=$PATH" avfs test

      - name: Run tests on non linux systems
        if: ${{ !startsWith(matrix.os, 'ubuntu') }}
        run: avfs test

      - name: Run race tests
        run: avfs race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        env:
          OS: ${{ matrix.os }}
          GO: ${{ matrix.go }}
        with:
          env_vars: OS,GO
          files: ./coverage/cover_test.txt,./coverage/cover_race.txt
          flags: unittests
          verbose: true
