name: CI
on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go: [1.23.x, 1.24.x]
        os: [ubuntu-latest, windows-latest]
        setostype: [setostype_on, setostype_off]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go }}

      - name: golangci-lint on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        uses: golangci/golangci-lint-action@v8

      - name: Install mage & avfs binaries
        run: go run mage/build.go

      - name: Run tests as an unprivileged user
        run: avfs test

      - name: Run tests as an unprivileged user with SetOsType
        env:
          GOFLAGS: "-tags=avfs_setostype"
        if: ${{ matrix.setostype == 'on' }}
        run: avfs test

      - name: Run tests as root
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: avfs testAsRoot

      - name: Run tests as root with SetOsType
        env:
          GOFLAGS: "-tags=avfs_setostype"
        if: ${{ startsWith(matrix.os, 'ubuntu') && matrix.setostype == 'on' }}
        run: avfs testAsRoot

      - name: Run race tests
        run: avfs race

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          os: ${{ matrix.os }}
          go: ${{ matrix.go }}
          setostype: ${{ matrix.setostype }}
        with:
          files: tmp/avfs-cover-*.txt
          env_vars: os,go,setostype
          verbose: true

      - name: Run build tests on linux
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: avfs testbuild

